# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-22 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg_app', '0002_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='user_like',
            field=models.ManyToManyField(related_name='num_likes', to='log_reg_app.User'),
        ),
    ]
