# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-22 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg_app', '0003_quote_user_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='user_like',
        ),
    ]
